// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enrjmivxwhkwticwdqmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVucmptaXZ4d2hrd3RpY3dkcW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzU2NTAsImV4cCI6MjA2MTgxMTY1MH0.9CkLxze4gMQ5YXJqa8zFYYmj_k4sy1sx05Wttq8w3FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);